@extends('errors.layout')
@section('title', 'Không có quyền truy cập')
@section('code', '401')
@section('icon', 'lock')
@section('message', 'Bạn chưa đăng nhập hoặc phiên làm việc đã hết hạn. Vui lòng đăng nhập để tiếp tục.')
