@extends('errors.layout')
@section('title', 'Truy cập bị từ chối')
@section('code', '403')
@section('icon', 'block')
@section('message', 'Bạn không có quyền truy cập vào khu vực này. Nếu bạn cho rằng đây là sự nhầm lẫn, vui lòng liên hệ quản trị viên.')
