@extends('errors.layout')
@section('title', 'Phiên hết hạn')
@section('code', '419')
@section('icon', 'timer_off')
@section('message', 'Phiên làm việc của bạn đã hết hạn do không hoạt động trong một thời gian dài. Vui lòng tải lại trang và thử lại.')
