@extends('errors.layout')
@section('title', 'Quá nhiều yêu cầu')
@section('code', '429')
@section('icon', 'hourglass_empty')
@section('message', 'Bạn đã thao tác quá nhanh. Vui lòng đợi một lát trước khi tiếp tục để đảm bảo hệ thống hoạt động ổn định.')
